apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-demo
  template:
    metadata:
      labels:
        app: prometheus-demo
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:main-distroless
          ports:
            - containerPort: 9090
