apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-demo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-demo
  template:
    metadata:
      labels:
        app: grafana-demo
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:main-ubuntu
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: grafana
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: grafana@123
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-demo
  namespace: monitoring
spec:
  selector:
    app: grafana-demo
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
